import { execFileSync, spawn as nodeSpawn } from "node:child_process";
import { writeFileSync, unlinkSync, existsSync } from "node:fs";
import { join } from "node:path";
import { tmpdir, homedir } from "node:os";
import net from "node:net";
import {
  getPlatform,
  chipSupportsNestedVirt,
  getAppleChip,
  getMacosVersion,
  isLimaInstalled,
  getLimaInstanceInfo,
  limaExec,
  limactlSync,
} from "../platform.js";

const INSTANCE_NAME = "hearth";
const DEFAULT_CPUS = 4;
const DEFAULT_MEMORY = "4GiB";
const DEFAULT_DISK = "50GiB";
const DAEMON_LOG = "/tmp/hearth-daemon.log";
const DAEMON_PORT = 7117;

export async function limaCommand(args: string[]): Promise<void> {
  const subcommand = args[0];

  switch (subcommand) {
    case "setup":
      return limaSetup(parseSetupArgs(args.slice(1)));
    case "start":
      return limaStart();
    case "stop":
      limaStop();
      return;
    case "status":
      await limaStatus();
      return;
    case "teardown":
      limaTeardown();
      return;
    case "shell":
      limaShell();
      return;
    default:
      printLimaUsage();
      process.exit(subcommand ? 1 : 0);
  }
}

interface SetupOpts {
  cpus: number;
  memory: string;
}

function parseSetupArgs(args: string[]): SetupOpts {
  const opts: SetupOpts = { cpus: DEFAULT_CPUS, memory: DEFAULT_MEMORY };
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--cpus" && args[i + 1]) {
      opts.cpus = parseInt(args[++i], 10);
      if (isNaN(opts.cpus) || opts.cpus < 1) {
        console.error("ERROR: --cpus must be a positive integer");
        process.exit(1);
      }
    } else if (args[i] === "--memory" && args[i + 1]) {
      const mem = args[++i];
      if (!/^\d+[KMGT]iB$/.test(mem)) {
        console.error("ERROR: --memory must match format like 4GiB, 512MiB, 1TiB");
        process.exit(1);
      }
      opts.memory = mem;
    }
  }
  return opts;
}

function printLimaUsage(): void {
  console.log("Usage: hearth lima <command>");
  console.log("");
  console.log("Commands:");
  console.log("  setup      Create and provision Lima VM for macOS");
  console.log("  start      Start Lima VM and daemon");
  console.log("  stop       Stop daemon and Lima VM");
  console.log("  status     Show Lima VM and daemon status");
  console.log("  teardown   Destroy Lima VM");
  console.log("  shell      Open a shell inside the Lima VM");
  console.log("");
  console.log("Options for setup:");
  console.log(`  --cpus <n>       Number of CPUs (default: ${DEFAULT_CPUS})`);
  console.log(`  --memory <size>  Memory size (default: ${DEFAULT_MEMORY})`);
}

// --- Preflight ---

function preflight(): void {
  const plat = getPlatform();
  if (plat !== "macos") {
    console.error("ERROR: hearth lima is for macOS only.");
    console.error("  On Linux, run: npx hearth setup");
    process.exit(1);
  }

  const chip = getAppleChip();
  console.log("  macOS: OK (Darwin arm64)");

  if (!chipSupportsNestedVirt()) {
    console.error(`  Apple Silicon: ${chip ?? "unknown"} (nested virtualization NOT supported)`);
    console.error("");
    console.error("ERROR: Your chip does not support nested virtualization.");
    console.error("  M3+ is required for local Lima support.");
    console.error("  For M1/M2, use a remote daemon: see docs/design-docs/platform-support.md");
    process.exit(1);
  }
  console.log(`  Apple Silicon: ${chip ?? "unknown"} (nested virtualization supported)`);

  const macosVer = getMacosVersion();
  if (macosVer < 15) {
    console.error(`  macOS version: ${macosVer} (requires 15+)`);
    console.error("");
    console.error("ERROR: macOS 15 (Sequoia) or later is required for nested virtualization.");
    process.exit(1);
  }

  if (!isLimaInstalled()) {
    console.error("  Lima: NOT FOUND");
    console.error("");
    console.error("ERROR: Lima is required. Install it:");
    console.error("  brew install lima");
    process.exit(1);
  }
  console.log("  Lima: OK");
}

// --- Lima YAML ---

function generateLimaConfig(opts: SetupOpts): string {
  return `# Generated by hearth lima setup
images:
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"
    arch: "aarch64"

cpus: ${opts.cpus}
memory: "${opts.memory}"
disk: "${DEFAULT_DISK}"

nestedVirtualization: true

mounts:
  - location: "~"
    writable: true

portForwards:
  - guestPort: ${DAEMON_PORT}
    hostPort: ${DAEMON_PORT}
    hostIP: "127.0.0.1"

provision:
  - mode: boot
    script: |
      #!/bin/bash
      [ -e /dev/kvm ] && chmod 666 /dev/kvm
      LIMA_USER=$(grep LIMA_CIDATA_USER= /mnt/lima-cidata/lima.env | head -1 | cut -d= -f2)
      mkdir -p /run/hearth
      chown "$LIMA_USER:$LIMA_USER" /run/hearth
      chmod 700 /run/hearth
  - mode: system
    script: |
      #!/bin/bash
      set -eux
      curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
      apt-get install -y nodejs
      curl -fsSL https://get.docker.com | bash -
      LIMA_USER=$(grep LIMA_CIDATA_USER= /mnt/lima-cidata/lima.env | head -1 | cut -d= -f2)
      usermod -aG docker "$LIMA_USER"
      usermod -aG kvm "$LIMA_USER"
`;
}

// --- Commands ---

async function limaSetup(opts: SetupOpts): Promise<void> {
  console.log("hearth lima setup\n");
  console.log("  Checking prerequisites...");

  preflight();

  const { status } = getLimaInstanceInfo(INSTANCE_NAME);

  if (status !== "not-found") {
    console.log(`\n  Lima instance "${INSTANCE_NAME}" already exists (${status}).`);
    console.log("  To recreate: hearth lima teardown && hearth lima setup");
    process.exit(1);
  }

  // Write lima config to temp file
  const configPath = join(tmpdir(), "hearth-lima.yaml");
  writeFileSync(configPath, generateLimaConfig(opts));

  try {
    console.log(`\n  Creating Lima instance "${INSTANCE_NAME}"...`);
    console.log(`    CPU: ${opts.cpus} cores`);
    console.log(`    Memory: ${opts.memory}`);
    console.log(`    Disk: ${DEFAULT_DISK}`);
    console.log("    Nested virtualization: enabled");
    console.log("    Shared mount: ~/.hearth (writable)");

    limactlSync(["create", "--name", INSTANCE_NAME, configPath]);
    console.log("    ✓ Instance created");

    console.log("\n  Starting Lima VM...");
    limactlSync(["start", INSTANCE_NAME]);
    console.log("    ✓ VM running");

    // Verify /dev/kvm is available inside the VM
    console.log("\n  Verifying nested virtualization...");
    try {
      limaExec(INSTANCE_NAME, "test -e /dev/kvm");
      console.log("    /dev/kvm: OK");
    } catch {
      console.error("    /dev/kvm: NOT FOUND");
      console.error("");
      console.error("ERROR: /dev/kvm not available inside Lima VM.");
      console.error("  Nested virtualization may not be working.");
      console.error("  Ensure your Mac has an M3+ chip and macOS 15+.");
      process.exit(1);
    }

    // Run hearth setup inside the VM
    // Set HEARTH_DIR so setup puts files on the shared macOS mount, not the Linux homedir.
    console.log("\n  Running hearth setup inside VM...");
    const hearthRoot = findHearthRoot();
    const hearthDir = limaHearthDir();
    // Run as root inside Lima — needed for docker and kvm access since group
    // membership from provisioning doesn't take effect until re-login.
    execFileSync("limactl", [
      "shell", INSTANCE_NAME, "--",
      "sudo", "bash", "-c", `cd '${shellEscape(hearthRoot)}' && HEARTH_DIR='${shellEscape(hearthDir)}' node dist/cli/hearth.js setup`,
    ], { stdio: "inherit" });

    // Start daemon
    console.log("\n  Starting daemon...");
    startDaemonInLima();

    // Verify daemon is accessible via Lima TCP port forwarding
    await waitForDaemon(DAEMON_PORT, 10000);
    console.log(`    ✓ Daemon listening on tcp://127.0.0.1:${DAEMON_PORT}`);

    console.log("\n  Setup complete. From macOS, use DaemonClient:\n");
    console.log('    import { DaemonClient } from "hearth";');
    console.log("    const client = new DaemonClient();");
    console.log("    await client.connect();");
    console.log("    const sandbox = await client.create();");
    console.log('    const result = await sandbox.exec("echo hello from a microVM");');
  } catch (err) {
    console.error(`\n  Setup failed: ${err instanceof Error ? err.message : err}`);
    console.error("  To clean up: hearth lima teardown");
    process.exit(1);
  } finally {
    try { unlinkSync(configPath); } catch {}
  }
}

async function limaStart(): Promise<void> {
  console.log("hearth lima start\n");

  const { status } = getLimaInstanceInfo(INSTANCE_NAME);

  if (status === "not-found") {
    console.error("ERROR: Lima instance not found. Run: hearth lima setup");
    process.exit(1);
  }

  const wasStarted = status === "running";

  if (status === "stopped") {
    console.log("  Starting Lima VM...");
    limactlSync(["start", INSTANCE_NAME]);
    console.log("  ✓ VM running");
  } else {
    console.log("  Lima VM already running");
  }

  // If the VM was already running, check if daemon is responsive
  if (wasStarted && await isDaemonResponsive(DAEMON_PORT)) {
    console.log("  Daemon already running");
    return;
  }

  console.log("  Starting daemon...");
  startDaemonInLima();
  await waitForDaemon(DAEMON_PORT, 10000);
  console.log(`  ✓ Daemon listening on tcp://127.0.0.1:${DAEMON_PORT}`);
}

function limaStop(): void {
  console.log("hearth lima stop\n");

  const { status } = getLimaInstanceInfo(INSTANCE_NAME);

  if (status === "not-found") {
    console.log("  No Lima instance found");
    return;
  }

  if (status === "running") {
    console.log("  Stopping daemon...");
    try {
      limaExec(INSTANCE_NAME, "pkill -f 'hearth.*daemon' || true");
    } catch {}
    console.log("  Stopping Lima VM...");
    limactlSync(["stop", INSTANCE_NAME]);
    console.log("  ✓ Stopped");
  } else {
    console.log("  Lima VM already stopped");
  }
}

async function limaStatus(): Promise<void> {
  const info = getLimaInstanceInfo(INSTANCE_NAME);

  if (info.status === "not-found") {
    console.log("Lima VM:  not created (run: hearth lima setup)");
    return;
  }

  let details = "";
  if (info.cpus || info.memory) {
    const cpus = info.cpus ?? "?";
    const mem = info.memory ? `${Math.round(info.memory / (1024 * 1024 * 1024))} GiB` : "?";
    details = ` (${cpus} CPU, ${mem} RAM)`;
  }

  console.log(`Lima VM:  ${info.status}${details}`);

  if (info.status === "running") {
    const responsive = await isDaemonResponsive(DAEMON_PORT);
    console.log(`Daemon:   ${responsive ? "running" : "not running"}`);
    console.log(`Address:  tcp://127.0.0.1:${DAEMON_PORT}`);
  }
}

function limaTeardown(): void {
  console.log("hearth lima teardown\n");

  const { status } = getLimaInstanceInfo(INSTANCE_NAME);
  if (status === "not-found") {
    console.log("  No Lima instance found");
    return;
  }

  console.log(`  Deleting Lima instance "${INSTANCE_NAME}"...`);

  if (status === "running") {
    try {
      limaExec(INSTANCE_NAME, "pkill -f 'hearth.*daemon' || true");
    } catch {}
  }

  limactlSync(["delete", INSTANCE_NAME, "--force"]);
  console.log("  ✓ Instance deleted");
  console.log("");
  console.log("  Note: ~/.hearth/ on macOS was preserved (shared mount).");
  console.log("  Snapshots and config still exist. Delete manually if needed.");
}

function limaShell(): void {
  const { status } = getLimaInstanceInfo(INSTANCE_NAME);
  if (status !== "running") {
    console.error(`ERROR: Lima instance is ${status === "not-found" ? "not created" : "stopped"}.`);
    console.error(status === "not-found" ? "  Run: hearth lima setup" : "  Run: hearth lima start");
    process.exit(1);
  }

  limactlSync(["shell", INSTANCE_NAME]);
}

// --- Helpers ---

function shellEscape(s: string): string {
  return s.replace(/'/g, "'\\''");
}

function findHearthRoot(): string {
  const candidates = [
    join(import.meta.dirname ?? "", "..", ".."),
    process.cwd(),
  ];
  const home = homedir();
  for (const dir of candidates) {
    if (existsSync(join(dir, "package.json"))) {
      // Lima mounts ~ into the guest — paths outside ~ won't be accessible
      if (dir !== home && !dir.startsWith(home + "/")) {
        throw new Error(
          `Hearth project at ${dir} is outside your home directory. ` +
          `Lima can only access files under ~. Move the project under ${home}.`,
        );
      }
      return dir;
    }
  }
  throw new Error("Could not find hearth project root");
}

/** The macOS-side hearth dir, accessible inside Lima via the virtiofs mount. */
function limaHearthDir(): string {
  return join(homedir(), ".hearth");
}

function startDaemonInLima(): void {
  const hearthRoot = findHearthRoot();
  const hearthDir = limaHearthDir();

  // Activate dm-thin pool if data files exist (pool doesn't survive VM reboots)
  try {
    execFileSync("limactl", ["shell", INSTANCE_NAME, "--", "sudo", "bash", "-c",
      `cd '${shellEscape(hearthRoot)}' && HEARTH_DIR='${shellEscape(hearthDir)}' node -e "import('./dist/vm/thin.js').then(m => m.activateThinPool())"`,
    ], { stdio: "pipe" });
  } catch {}

  // Daemon listens on both Unix socket (guest-local) and TCP (Lima port-forwards to host).
  // Run as root for dm-thin access (block-level CoW snapshots).
  nodeSpawn(
    "limactl",
    ["shell", INSTANCE_NAME, "--", "sudo", "bash", "-c",
      `cd '${shellEscape(hearthRoot)}' && HEARTH_DIR='${shellEscape(hearthDir)}' nohup node dist/cli/hearth.js daemon > ${DAEMON_LOG} 2>&1 &`,
    ],
    { stdio: "ignore", detached: true },
  ).unref();
}

/** Wait for the daemon TCP port to be responsive. */
function waitForDaemon(port: number, timeoutMs: number): Promise<void> {
  return new Promise((resolve, reject) => {
    const start = Date.now();
    const check = () => {
      if (Date.now() - start > timeoutMs) {
        let logHint = "";
        try {
          const log = limaExec(INSTANCE_NAME, `tail -20 ${DAEMON_LOG}`);
          if (log.trim()) logHint = `\nDaemon log:\n${log}`;
        } catch {}
        reject(new Error(`Timed out waiting for daemon on port ${port}${logHint}`));
        return;
      }

      const conn = net.connect({ host: "127.0.0.1", port });
      conn.once("connect", () => {
        conn.destroy();
        resolve();
      });
      conn.once("error", () => {
        conn.destroy();
        setTimeout(check, 500);
      });
    };
    check();
  });
}

/** Check if the daemon is listening on the given TCP port. */
function isDaemonResponsive(port: number): Promise<boolean> {
  return new Promise((resolve) => {
    const conn = net.connect({ host: "127.0.0.1", port });
    const timeout = setTimeout(() => {
      conn.destroy();
      resolve(false);
    }, 1000);
    conn.once("connect", () => {
      clearTimeout(timeout);
      conn.destroy();
      resolve(true);
    });
    conn.once("error", () => {
      clearTimeout(timeout);
      conn.destroy();
      resolve(false);
    });
  });
}
